version: "3.8"

services:
  staging:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next_staging
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.staging.example.com
    ports:
      - "3001:3000"

  production:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next_production
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.example.com
    ports:
      - "3000:3000"
