#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Start test build..."

npm run build

if [ $? -ne 0 ]; then
  echo "❌ Build failed, please fix the errors before pushing your code"
  exit 1
fi

echo "✅ Build successful! Push proceeding..."
